name: CI

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      
      # - name:  Install dependencies
      #   uses: npm install
      
      # - name: Linter
      #   uses: npm run lint
      
      # - name: Formatter
      #   uses: npm run prettier

      # - name: Test
      #   env:
      #     CI: true
      #   run: npm run test
      
      # - name: Build
      #   uses: npm run build