name: CI

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 15.5.1
      
      - name: Install dependencies
        run: npm install
      
      - name: Linter
        run: npm run lint
      
      - name: Formatter
        run: npm run prettier

      - name: Test
        env:
          CI: true
        run: npm run test
      
      - name: Build
        run: npm run build